name: pytorch_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13.3
  - numpy=2.2.5
  - pandas=2.2.3
  - matplotlib=3.10.1
  - pillow=11.2.1
  - tqdm=4.67.1
  - ipython=9.1.0
  - pip
  - pip:
    - torch==2.6.0
    - torchvision==0.21.0
    - transformers==4.52.4
    - einops==0.8.1
    - wandb==0.20.1
    - torchview==0.2.7
    - piq==0.8.0
    - kornia==0.8.1
    - opencv-python==4.12.0
